baseURL: https://recepten.rmhogervorst.nl
disablePathToLower: true
defaultMarkdownHandler: goldmark
languageCode: nl-nl
title: Mijn recepten
theme: gochowdown
googleAnalytics:
defaultcontentlanguage: nl
paginate: 30
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: R. H
  description: Recepten gebruikt door ons
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent:
  hidecredits: true
  hidecopyright: false
  showNavTitle: false            # Boolean: show site title in nav bar
  custom_css:
    - style.css
languages: "nl"
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Categorie
      weight: 6
      url: /category/
    - name: Type gerecht
      weight: 2
      url: /type_gerecht/
    - name: Tags
      weight: 4
      url: /tags/
    - name: Ingredienten
      weight: 1
      url: /ingredients/

taxonomies:
  category: category
  cuisine: cuisine
  tag: tags
  ingredient: ingredients
  week: weeks
  diet: diets
  type_gerecht: type_gerecht

outputs:
  page:
    - HTML
    - json
  section:
    - HTML
    - json

markup:
  goldmark:
    renderer:
      unsafe: true

# Diet specifics, ingredients that should not be in there
specialdiets:
  paraberk: [appel, kers, kiwi, tomaat]
