baseURL: https://recepten.rmhogervorst.nl
disablePathToLower: true
defaultMarkdownHandler: goldmark
languageCode: nl-nl
title: Mijn recepten
theme: gochowdown
googleAnalytics:
defaultcontentlanguage: nl
#languages: "nl"
paginate: 50
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title

params:
  author: R. H
  description: Recepten gebruikt door ons
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent:
  hidecredits: true
  hidecopyright: false
  showNavTitle: false            # Boolean: show site title in nav bar
  custom_css:
    - style.css


menu:
  main:
    - name: "[oventijden]"
      weight: 1
      url: /overig/oventijden/
    - name: Home
      weight: 2
      url: /
    - name: "keuken"
      url: /cuisine/
    - name: categorie
      weight: 6
      url: /category/
    - name: type gerecht
      weight: 2
      url: /type_gerecht/
    - name: tags
      weight: 4
      url: /tags/
    - name: ingredienten
      weight: 3
      url: /ingredients/
    - name: Lijst
      weight: 2
      url: /recipes/

taxonomies:
  category: category
  cuisine: cuisine
  tag: tags
  ingredient: ingredients
  diet: diets
  type_gerecht: type_gerecht

outputs:
  page:
    - HTML
    - json
  section:
    - HTML
    - json

markup:
 goldmark:
   renderer:
     unsafe: true

#Diet specifics, ingredients that should not be in there
specialdiets:
 paraberk: [appel, kers, kiwi, tomaat]
